### ISSUE TITLE
Actions like combat should be broadcast to others in the same room.

### ISSUE THREAD

**Issue by seanohue** [shawncplus/ranviermud#154] opened 2017-02-27 03:45 UTC
If it is visible, player characters should see it. I'm setting the ground work for this in the PvP PR.

**Comment by shawncplus** [comment] 2017-02-27 05:40
I disagree, perhaps it should be a setting. Combat is the spammiest thing in a MUD and seeing all the actions going on from all players would be incredibly spammy. Maybe even the first instance of the player preferences where they can opt in to seeing combat from others

**Comment by marado** [comment] 2017-02-27 09:22
I'm all for realism and agree with @seanohue 's suggestion. But even on crowded MUDs with heavy fight scenes, I don't remember this being so (despite the spam wall the causes, sometimes mitigated by the use of colours). Also, knowing what's going on in the fight in front of you will help you decide whether to ignore it, join in or flee from the scene; staying there might mean getting a punch yourself.

**Comment by seanohue** [comment] 2017-02-27 12:19
I agree that there could be a preference for verbose or brief combat descriptions, I still think there should be _something_. As of right now, there's no indication that combat has begun, or even that someone involved in it has died (though I added the latter on my branch).

As a bare minimum, I'd like to see the following:
- You are notified when characters start fighting.
- If you walk into a room and characters are fighting, you are notified.
- You are notified when a fight ends due to fleeing/death/whatnot.

**Comment by shawncplus** [comment] 2017-02-27 15:30
@seanohue I agree with your list. Perhaps for item 2 instead of being notified you simply see it in the `look` string.

    [Player] Admin
    [Player] Shawn, fighting A Rat
    [NPC] A Rat, fighting Shawn

**Comment by seanohue** [comment] 2017-02-27 16:04
@shawncplus I like that idea, especially because players already `autolook` on entering a room.

I will probably also eventually add broadcasting to the room on using certain skills, since I don't think that is currently implemented. I think it'd be good to include so bundle developers see how it'd be done in terms of best practices.

**Comment by samjaninf** [comment] 2017-02-27 18:46
I agree with the broadcasting certain skills to the room especially AoE skills as that might or might not affect other people in the room negatively since PvP was mentioned.

**Comment by seanohue** [comment] 2017-02-27 18:49
Yeah, regardless, the PR I put up makes it fairly easy to do so and it'd be good practice to do so in the base modules as an example for bundle developers.

In general, it's a good rule of thumb in virtual worlds to make anything that happens visible to anyone who can "see" it, otherwise you end up with stuff happening "magically" (and not in a good, fun, fantastical way). So, entering/leaving a room, emoting, saying, giving another player an item, picking up an item, etc.

**Comment by shawncplus** [comment] 2017-08-13 02:57
Closing this as the PR was merged along time ago

**Closed by shawncplus** 2017-08-13 02:57 UTC
Labels: Discussion
